# Cloudflare Pages configuration for SumTube Bot frontend
name = "sumtubebot"
compatibility_date = "2024-01-01"

# Pages-specific configuration
pages_build_output_dir = "dist/client"

[build]
command = "npm run build:client"
cwd = "."
watch_dir = "client"

[build.environment_variables]
VITE_DISCORD_APPLICATION_ID = "your_discord_application_id_here"

# Security headers
[[headers]]
for = "/*"
[headers.values]
  X-Frame-Options = "DENY"
  X-Content-Type-Options = "nosniff"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "strict-origin-when-cross-origin"
  
# SPA routing - serve index.html for all routes
[[redirects]]
from = "/*"
to = "/index.html"
status = 200 