# Cloudflare Pages configuration for SumTube Bot frontend
name = "sumtubebot"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist/client"

# Pages-specific configuration
pages_build_output_dir = "dist/client" 